* Notes on things to remember and consider
  General notes on topics that are important to remember
  Kind of a TODO
** Centered pictures
   It seems that the QNN struggles a lot with recognising signs that aren't completely
   within the 32x32 picture
   It is not enough that it is centered, the sign must also be within the
   boundaries of the picture
** Test pictures
   Need to create different versions of the pictures of the signs to test with
*** Variations
    Rotation
    From the side
    Out on the egdes/less visible
** Overview
   Ane will draw pictures of the overview of the simulation
** Seize the means of production
   Get pictures from the camera when that part is ready
** Observations
   Size and brightness is less important than centered traffic signs
   QNN har godt nattesyn!
   Se tolkning av stoptest2.jpg og stoptest3.jpg



* Timeline
  Deadlines for when we want to have completed tasks
** Mon 09/10
*** More test cases
    More pictures to test with the QNN
*** Output values
    Look at which values we can expect
    What should be the cut-off?
*** Cleaner code
    Something something current year
** Mon 16/10
*** Signals
    Which signals to send to the PCB?
    Dependent on the output values we've found
*** "Complete system"
    If the webcam part is more or less functional, we can create a more complete system
**** Real world to motors
     Object -> picture -> preprocessing -> QNN -> signal -> reaction
** Onwards
   Improve the simulation
   Hard to say anything in particular until we know what we have to work with
*** Work on other features?
    If there's not that much to be done, maybe help out with other parts of the project
